### ISSUE TITLE
Deploy MVP for demonstration

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#153]
1. [x] Front-end: https://kuai-mvp-dapp-ui.vercel.app/
2. [ ] Backend

--------------

Backend is under deployment

**Comment by Keith-CY** [comment]
How about the CI/CD of deployment @PainterPuppets

**Comment by Keith-CY** [comment]
> How about the CI/CD of deployment @PainterPuppets

Any update?

**Comment by Keith-CY** [comment]
Any problem with deploying the mvp dapp by github action? @PainterPuppets

**Comment by PainterPuppets** [comment]
code in here: https://github.com/ckb-js/kuai/pull/167
