### ISSUE TITLE
Design the ckb contract for MVP DApp Demo

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#192]
At the early stage, we have a MVP DApp(https://github.com/ckb-js/kuai/issues/54) to verify data manipulation on a cell.

Now we are going to support on-chain contracts in kuai, so the MVP DApp should also cover the on-chain verification. 

Ref: [add contract module in kuai project](https://github.com/ckb-js/kuai/issues/93)

**Comment by Keith-CY** [comment]
How is it going

**Comment by zhengjianhui** [comment]
> How is it going

Reference MVP [feature requirements](https://github.com/ckb-js/kuai/issues/54), I think providing the simplest CKB contract and storing JSON in the contract would be sufficient.


Data structure:
```
Data:
	info: infomation in json format
Type:
	code_hash: MVP_TYPE
	args: type_id
Lock:
	user lock

```

**Comment by yanguoyu** [comment]
I think we should also design a simple way to verify data in the MVP contract.

**Comment by zhengjianhui** [comment]
> I think we should also design a simple way to verify data in the MVP contract.

Here, we can follow [the definition of namespaces in .bit](https : //docs.did.id/developers/records-key-namespace) and use the first-level namespace as the validation object, which means that only four namespaces, which are the same as .bit, are allowed at the first-level.

**Comment by zhengjianhui** [comment]
I feel that implementing a JSON parser in a contract is too expensive, and there may be issues with recursion or looping. Therefore, I am considering using Molecule or other data storage solutions. I need to research Molecule further, and I will provide more details later.

**Comment by zhengjianhui** [comment]
[Data definitions ](https://github.com/zhengjianhui/kuai-mvp-contract/blob/master/types/src/kuai_mvp_data.rs)for molecule versions and related implementations

**Comment by Keith-CY** [comment]
> [Data definitions ](https://github.com/zhengjianhui/kuai-mvp-contract/blob/master/types/src/kuai_mvp_data.rs?rgh-link-date=2023-04-25T12%3A35%3A01Z)for molecule versions and related implementations

Please add your idea about JSON serialization here

**Comment by zhengjianhui** [comment]
> > [Data definitions ](https://github.com/zhengjianhui/kuai-mvp-contract/blob/master/types/src/kuai_mvp_data.rs?rgh-link-date=2023-04-25T12%3A35%3A01Z)for molecule versions and related implementations
> 
> Please add your idea about JSON serialization here

[JSON serialization](https://github.com/zhengjianhui/kuai-mvp-contract/tree/feat/json-support)
