### ISSUE TITLE
Design `Store` model

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#2]
- [ ] as an actor factor: https://github.com/ckb-js/kuai/issues/4
- [ ] default storage layout
- [ ] pattern to gather cells
- [ ] interfaces
    - [ ] new(pattern): fetch cells by the specific pattern and initialize a `Store` model
    - [ ] destroy(): remove data in the `Store` model
    - [ ] duplicate(): create a new `Store` model from plain cells with the same data
    - [ ] sync(blockNumber?): load data with pattern defined on initialization at a specific block number
    - [ ] get(path): get a value at the specific path
    - [ ] set(path, value): update a value at the specific path
    - [ ] delete(path): remove key-value pair at the specific path
- [ ] metadata of a storage
	- [ ] schema
	- [ ] serialization
	- [ ] how to share/propagate metadata
- [ ] lazy evaluation of updates

**Comment by Keith-CY** [comment]
A rough to-do list of `Store` model was added to this issue. Other models have their own issues
- Contract: https://github.com/ckb-js/kuai/issues/3
- Token: https://github.com/ckb-js/kuai/issues/5

We can talk a bit more about details and I'll enrich the to-do list along with the discussion. @janx @homura @felicityin @yanguoyu

**Comment by yanguoyu** [comment]
Define cell storage struct to gather by the specific pattern.

**Comment by yanguoyu** [comment]
Define cell storage struct to gather by the specific pattern.

**Comment by Keith-CY** [comment]
> Define cell storage struct to gather by the specific pattern.

Does this mean how to match a pattern with a given cell storage struct?

Take the issues in GitHub as an example

If we are building an issue system on-chain and every issue is stored as a cell, it would be structured as
```
interface Issue {
  open: boolean
  updated_at: timestamp
  label: Array<string>
  author: User
}
```

![image](https://user-images.githubusercontent.com/7271329/194736952-85549420-c6d8-47f9-b4f5-3506fb95bde8.png)

While we can filter cells/issues out by a pattern as `is:open sort:updated-desc author:@me`

![image](https://user-images.githubusercontent.com/7271329/194736973-5039fec6-6fe7-4037-beb2-7faa2cf3bc70.png)

Would the question be `what's the default struct of a cell off-chain and corresponding patterns `?

**Comment by yanguoyu** [comment]
> interface Issue {
  open: boolean
  updated_at: timestamp
  labels: Array<string>
  author: User
}
Would the question be what's the default struct of a cell off-chain and corresponding patterns ?

Yeah, on the other hand, how to store this information on the chain? Or how to transform these data to bytecode and store them in the cell?

**Comment by Keith-CY** [comment]
> > interface Issue {
> > open: boolean
> > updated_at: timestamp
> > labels: Array
> > author: User
> > }
> > Would the question be what's the default struct of a cell off-chain and corresponding patterns ?
> 
> Yeah, on the other hand, how to store this information on the chain? Or how to transform these data to bytecode and store them in the cell?

That's the detail we're going to confirm in this issue.

**Comment by yanguoyu** [comment]
I have designed something about `Store` like this. Please have a review. @Keith-CY @homura @IronLu233 
1. Schema:
```typescript
type StorageType = 'json' | 'molecule'
type StorageLoc = 'data' | 'witness'
export const loc = Symbol('loc')

type DataType = 'string' | 'number' | 'boolean'

export interface Schema {
  [field: string]: DataType | DataType[] | { [field: string]: DataType | DataType[] }
  [loc]?: StorageLoc
}
```
Make assume, a Dapp's scheme is unique. Then we can transfer it to kuai as a parameter.
Let me define a entry class:
```typescript
class App {
  schema: Schema[]
  storageType: StorageType
  offset: Partial<Record<StorageLoc, number>>
  registerSchema(schema: Schema[], type: StorageType = 'json', offset?: Partial<Record<StorageLoc, number>>) {
    this.schema = schema
    this.storageType = type
    this.offset = offset
  }
  sync(tx: CKBComponents.Transaction) {
    //Get State from tx by S and transfter State to Store by message
    const data = tx.outputsData
    const witness = tx.witnesses
    for (let i = 0; i < data.length; i++) {
      const item = data[i];
      const addStates = []
      const removeStates = []
      const inDataFields = this.schema.filter(v => v[loc] === 'data')
      const inWitnessFields = this.schema.filter(v => v[loc] === 'witness')
      if (inDataFields.length) {
        const offset = this.offset.data || 0
        // Deserialization data by offset and type
      }
      if (inWitnessFields.length) {
        const offset = this.offset.witness || 0
        // Deserialization witness by offset and type
      }
      // send message to actors to sync data
    }
  }
}
```

Then Dapp developers can transfer schema like this:
```typescript
const bitSchema: Schema[] = [
  {
    name: 'string',
    version: 'string',
    [loc]: 'data'
  },
  {
    version: 'string',
    [loc]: 'data'
  },
  {
    [loc]: 'witness',
    domain: {
      name: 'string',
      createTime: 'string',
    }
  }
]
const app = new App()
app.registerSchema(bitSchema)
app.start()
```
2. Pattern
I design patterns to match data in the chain by fields and match operations or match by RegExp
Avoid the patterns becoming complex, I don't design nest patterns.
```typescript
export interface PatternItem {
  field: string
  match: {
    op: 'eq' | 'lt' | 'gt' | 'lte' | 'gte' | 'in'
    value: any
  } | RegExp
}

export type Pattern = {
  aggregate: 'OR' | 'AND'
  patterns: PatternItem[]
}[] | PatternItem

```
I can define a pattern to match `AAAAA` or match `BBBBB`
```typescript
[
  {
    aggregate: 'or',
    patterns: [
      {
        field: 'data.domain',
        match: {
          op: 'in',
          value: 'AAAAA'
        }
      },
      {
        field: 'data.domain',
        match: {
          op: 'in',
          value: 'BBBBB'
        }
      }
    ]
  }
]
```
Or simply define a pattern
```typescript
{
        field: 'data.domain',
        match: {
          op: 'in',
          value:  new RegExp('^(A|B){5}$')
        }
}
```
4. Store
The `Store` receives data from the root actor to add or remove data storage by pattern, stores messages in memory, then calculates finally States by messages.
The `Store` save `States` by key -> value, the key is the Outpoint to string, value is deserialized from a transaction by a schema.
```typescript
export class Store<S extends State = State, M extends Message = Message> extends Actor {
  pattern: Pattern;
  protected states: Record<OutPointString, S> = {}
  private messageList: M[] = []

  constructor(pattern: Pattern) {
    super()
    this.pattern = pattern
  }

  // sync from tx or database
  private addState(addStates: Record<OutPointString, S>) {
    this.states = {
      ...this.states,
      ...addStates
    }
  }

  // sync from tx
  private removeState(keys: OutPointString[]) {
    keys.forEach(key => {
      delete this.states[key]
    })
  }

  duplicate() {
    const store =  new Store(this.pattern)
    // copy states and messages
    return store
  }

  handle(message: M) {
    switch (message.type) {
      case 'add-state':
        // if match pattern
        this.addState(message.data)
        break;
      case 'remove-state':
        // if match pattern
        this.removeState(message.data)
        break;
      default:
        break;
    }
  }

  get(path: StataPath) {
    if (path.path) {
      return this.states[path.key][path.path]
    }
    return this.states[path.key]
  }
  set(path: StataPath, value: any) {
    if (path.path) {
      this.states[path.key][path.path] = value
    }
    this.states[path.key] = value
  }

  remove(path: StataPath) {
    if (path.path) {
      delete this.states[path.key][path.path]
    }
    delete this.states[path.key]
  }

  finalize() {
    this.messageList.forEach(message => {
      this.handle(message)
    })
    return this.states;
  }
}
```

**Comment by Keith-CY** [comment]
> I have designed something about `Store` like this. Please have a review. @Keith-CY @homura @IronLu233
> 
> 1. Schema:
> 
> ```ts
> type StorageType = 'json' | 'molecule'
> type StorageLoc = 'data' | 'witness'
> export const loc = Symbol('loc')
> 
> type DataType = 'string' | 'number' | 'boolean'
> 
> export interface Schema {
>   [field: string]: DataType | DataType[] | { [field: string]: DataType | DataType[] }
>   [loc]?: StorageLoc
> }
> ```
> 
> Make assume, a Dapp's scheme is unique. Then we can transfer it to kuai as a parameter. Let me define a entry class:
> 
> ```ts
> class App {
>   schema: Schema[]
>   storageType: StorageType
>   offset: Partial<Record<StorageLoc, number>>
>   registerSchema(schema: Schema[], type: StorageType = 'json', offset?: Partial<Record<StorageLoc, number>>) {
>     this.schema = schema
>     this.storageType = type
>     this.offset = offset
>   }
>   sync(tx: CKBComponents.Transaction) {
>     //Get State from tx by S and transfter State to Store by message
>     const data = tx.outputsData
>     const witness = tx.witnesses
>     for (let i = 0; i < data.length; i++) {
>       const item = data[i];
>       const addStates = []
>       const removeStates = []
>       const inDataFields = this.schema.filter(v => v[loc] === 'data')
>       const inWitnessFields = this.schema.filter(v => v[loc] === 'witness')
>       if (inDataFields.length) {
>         const offset = this.offset.data || 0
>         // Deserialization data by offset and type
>       }
>       if (inWitnessFields.length) {
>         const offset = this.offset.witness || 0
>         // Deserialization witness by offset and type
>       }
>       // send message to actors to sync data
>     }
>   }
> }
> ```
> 
> Then Dapp developers can transfer schema like this:
> 
> ```ts
> const bitSchema: Schema[] = [
>   {
>     name: 'string',
>     version: 'string',
>     [loc]: 'data'
>   },
>   {
>     version: 'string',
>     [loc]: 'data'
>   },
>   {
>     [loc]: 'witness',
>     domain: {
>       name: 'string',
>       createTime: 'string',
>     }
>   }
> ]
> const app = new App()
> app.registerSchema(bitSchema)
> app.start()
> ```
> 
> 2. Pattern
>    I design patterns to match data in the chain by fields and match operations or match by RegExp
>    Avoid the patterns becoming complex, I don't design nest patterns.
> 
> ```ts
> export interface PatternItem {
>   field: string
>   match: {
>     op: 'eq' | 'lt' | 'gt' | 'lte' | 'gte' | 'in'
>     value: any
>   } | RegExp
> }
> 
> export type Pattern = {
>   aggregate: 'OR' | 'AND'
>   patterns: PatternItem[]
> }[] | PatternItem
> ```
> 
> I can define a pattern to match `AAAAA` or match `BBBBB`
> 
> ```ts
> [
>   {
>     aggregate: 'or',
>     patterns: [
>       {
>         field: 'data.domain',
>         match: {
>           op: 'in',
>           value: 'AAAAA'
>         }
>       },
>       {
>         field: 'data.domain',
>         match: {
>           op: 'in',
>           value: 'BBBBB'
>         }
>       }
>     ]
>   }
> ]
> ```
> 
> Or simply define a pattern
> 
> ```ts
> {
>         field: 'data.domain',
>         match: {
>           op: 'in',
>           value:  new RegExp('^(A|B){5}$')
>         }
> }
> ```
> 
> 4. Store
>    The `Store` receives data from the root actor to add or remove data storage by pattern, stores messages in memory, then calculates finally States by messages.
>    The `Store` save `States` by key -> value, the key is the Outpoint to string, value is deserialized from a transaction by a schema.
> 
> ```ts
> export class Store<S extends State = State, M extends Message = Message> extends Actor {
>   pattern: Pattern;
>   protected states: Record<OutPointString, S> = {}
>   private messageList: M[] = []
> 
>   constructor(pattern: Pattern) {
>     super()
>     this.pattern = pattern
>   }
> 
>   // sync from tx or database
>   private addState(addStates: Record<OutPointString, S>) {
>     this.states = {
>       ...this.states,
>       ...addStates
>     }
>   }
> 
>   // sync from tx
>   private removeState(keys: OutPointString[]) {
>     keys.forEach(key => {
>       delete this.states[key]
>     })
>   }
> 
>   duplicate() {
>     const store =  new Store(this.pattern)
>     // copy states and messages
>     return store
>   }
> 
>   handle(message: M) {
>     switch (message.type) {
>       case 'add-state':
>         // if match pattern
>         this.addState(message.data)
>         break;
>       case 'remove-state':
>         // if match pattern
>         this.removeState(message.data)
>         break;
>       default:
>         break;
>     }
>   }
> 
>   get(path: StataPath) {
>     if (path.path) {
>       return this.states[path.key][path.path]
>     }
>     return this.states[path.key]
>   }
>   set(path: StataPath, value: any) {
>     if (path.path) {
>       this.states[path.key][path.path] = value
>     }
>     this.states[path.key] = value
>   }
> 
>   remove(path: StataPath) {
>     if (path.path) {
>       delete this.states[path.key][path.path]
>     }
>     delete this.states[path.key]
>   }
> 
>   finalize() {
>     this.messageList.forEach(message => {
>       this.handle(message)
>     })
>     return this.states;
>   }
> }
> ```

1. `number` in JavaScript is obscure and error-prone because it has a limit, maybe `decimal`, `big number`, `big decimal` are more clear;
2. `Schema` could be recursive, as `[field: string]: Schema` so each field would have a `loc` attribute to specify whether it's in data or witness.
3. Why is `sync` method receiving a `transaction`. If it's updated by a transaction, there would be a series of updates during a block;

**Comment by yanguoyu** [comment]
> number in JavaScript is obscure and error-prone because it has a limit, maybe decimal, big number, big decimal are more clear;

It's a good suggestion, I will update it later.

> Schema could be recursive, as [field: string]: Schema so each field would have a loc attribute to specify whether it's in data or witness.

I think we should make the `loc` at the outermost. If `loc` is in recursive data, the `data` object maybe have some fields that will save in witness. Like this, it may make it confusing.

```typescript
const bitSchema: Schema[] = [
  {
    name: 'string',
    version: 'string',
    [loc]: 'data',
    domain: {
      [loc]: 'witness',
      name: 'string',
      createTime: 'string',
    }
  }
]

```

> Why is sync method receiving a transaction. If it's updated by a transaction, there would be a series of updates during a block;

It should sync from a block, I just described how it will deserialize from a transaction.

**Comment by Keith-CY** [comment]
I see the design was updated 2 days ago, is it ready for review again?
