### ISSUE TITLE
Support deploying contracts with multisig

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#233]
<del>Multisig protocol in progress: https://www.notion.so/cryptape/CKB-Combine-Lock-da160ce803ba43c19950694fac469603</del>
The multisig protocol mentioned above is a general solution, which is too complex in this case.

Supporting `secp256k1_blake160_multisig_all` to deploy a contract is enough

**Comment by Keith-CY** [comment]
PR: https://github.com/ckb-js/kuai/pull/264

**Comment by Keith-CY** [comment]
Please open a new issue for feedback from .bit members and the corresponding optimization design

**Comment by PainterPuppets** [comment]
Opened a new issue https://github.com/ckb-js/kuai/issues/276
