### ISSUE TITLE
Support infrastructural scripts on devnet

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#235]
The following are the most prevailing scripts that not provided on devnet by default

- [ ] Anyone can pay: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0026-anyone-can-pay/0026-anyone-can-pay.md
- [ ] Simple UDT: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0025-simple-udt/0025-simple-udt.md
- [ ] CoTA: unrevealed
- [ ] Omnilock: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0042-omnilock/0042-omnilock.md

But they are widely used in dapps, and are usually inevitable in dapp development. It would be quite helpful if they are out-of-the-box in kuai

**Comment by Daryl-L** [comment]
What I designed is as follow.

First, I will provider a method named `depolyInfraScripts` in `CkbDockerNetwork` for cli to call, cli will call this method immediately while the node starting. Then I will create a folder which stores the scripts should be deployed.

In file https://github.com/ckb-js/kuai/blob/11d213db47e9ba025e209ea26dbe612ea5967604/packages/core/src/builtin-tasks/node.ts#L27

```typescript
const ckbDockerNetwork = new CkbDockerNetwork()
await ckbDockerNetwork.start({
  port: port.toString(),
  detached,
  genesisAccountArgs: genesisArgs,
})
await ckbDockerNetwork.depolyInfraScripts()
```

Create a folder to store scripts in package `docker-node`.
```
- docker-node
- - scripts
- - - sudt
- - - omnilock
- - - acp
```

In file https://github.com/ckb-js/kuai/blob/11d213db47e9ba025e209ea26dbe612ea5967604/packages/docker-node/src/ckb-docker-network.ts#L9
```typescript
deploy() {
  // load scripts bin from scripts file
  // deploy them by prepared account
  // output the cell info of deployed scripts to command line and file
```


What I inspires me is Force Bridge. https://github.com/Magickbase/force-bridge/blob/feature-nervos-to-ethereum/offchain-modules/packages/x/src/ckb/tx-helper/deploy.ts
Please correct me if I was wrong.

**Comment by Keith-CY** [comment]
> What I designed is as follow.
> 
> First, I will provider a method named `depolyInfraScripts` in `CkbDockerNetwork` for cli to call, cli will call this method immediately while the node starting. Then I will create a folder which stores the scripts should be deployed.
> 
> In file
> 
> https://github.com/ckb-js/kuai/blob/11d213db47e9ba025e209ea26dbe612ea5967604/packages/core/src/builtin-tasks/node.ts#L27
> 
> ```ts
> const ckbDockerNetwork = new CkbDockerNetwork()
> await ckbDockerNetwork.start({
>   port: port.toString(),
>   detached,
>   genesisAccountArgs: genesisArgs,
> })
> await ckbDockerNetwork.depolyInfraScripts()
> ```
> 
> Create a folder to store scripts in package `docker-node`.
> 
> ```
> - docker-node
> - - scripts
> - - - sudt
> - - - omnilock
> - - - acp
> ```
> 
> In file
> 
> https://github.com/ckb-js/kuai/blob/11d213db47e9ba025e209ea26dbe612ea5967604/packages/docker-node/src/ckb-docker-network.ts#L9
> 
> ```ts
> deploy() {
>   // load scripts bin from scripts file
>   // deploy them by prepared account
>   // output the cell info of deployed scripts to command line and file
> ```
> 
> What I inspires me is Force Bridge. [Magickbase/force-bridge@`feature-nervos-to-ethereum`/offchain-modules/packages/x/src/ckb/tx-helper/deploy.ts](https://github.com/Magickbase/force-bridge/blob/feature-nervos-to-ethereum/offchain-modules/packages/x/src/ckb/tx-helper/deploy.ts?rgh-link-date=2023-04-23T04%3A35%3A38Z) Please correct me if I was wrong.

An entry to extend the script list on devnet should be provided for users to add custom scripts.

---

Since we're going to support the deployment of multiple contracts(https://github.com/ckb-js/kuai/issues/230) and binaries(https://github.com/ckb-js/kuai/issues/231), how about specifying a directory full of contract binaries and a metadata file as an index of the contracts to deploy, e.g.

```json
{
  "sudt": {
    "path": "built-in/sudt"
  },
  "custom": {
    "path": "./custom"
  }
}
```

And the deployed tx info will be appended into the metadata file for reference in dapp.

**Comment by Daryl-L** [comment]
> > What I designed is as follow.
> > First, I will provider a method named `depolyInfraScripts` in `CkbDockerNetwork` for cli to call, cli will call this method immediately while the node starting. Then I will create a folder which stores the scripts should be deployed.
> > In file
> > https://github.com/ckb-js/kuai/blob/11d213db47e9ba025e209ea26dbe612ea5967604/packages/core/src/builtin-tasks/node.ts#L27
> > 
> > ```ts
> > const ckbDockerNetwork = new CkbDockerNetwork()
> > await ckbDockerNetwork.start({
> >   port: port.toString(),
> >   detached,
> >   genesisAccountArgs: genesisArgs,
> > })
> > await ckbDockerNetwork.depolyInfraScripts()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Create a folder to store scripts in package `docker-node`.
> > ```
> > - docker-node
> > - - scripts
> > - - - sudt
> > - - - omnilock
> > - - - acp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In file
> > https://github.com/ckb-js/kuai/blob/11d213db47e9ba025e209ea26dbe612ea5967604/packages/docker-node/src/ckb-docker-network.ts#L9
> > 
> > ```ts
> > deploy() {
> >   // load scripts bin from scripts file
> >   // deploy them by prepared account
> >   // output the cell info of deployed scripts to command line and file
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What I inspires me is Force Bridge. [Magickbase/force-bridge@`feature-nervos-to-ethereum`/offchain-modules/packages/x/src/ckb/tx-helper/deploy.ts](https://github.com/Magickbase/force-bridge/blob/feature-nervos-to-ethereum/offchain-modules/packages/x/src/ckb/tx-helper/deploy.ts?rgh-link-date=2023-04-23T04%3A35%3A38Z) Please correct me if I was wrong.
> 
> An entry to extend the script list on devnet should be provided for users to add custom scripts.
> 
> Since we're going to support the deployment of multiple contracts(#230) and binaries(#231), how about specifying a directory full of contract binaries and a metadata file as an index of the contracts to deploy, e.g.
> 
> ```json
> {
>   "sudt": {
>     "path": "built-in/sudt"
>   },
>   "custom": {
>     "path": "./custom"
>   }
> }
> ```
> 
> And the deployed tx info will be appended into the metadata file for reference in dapp.

That's a good idea. I will change the file as follow.

```javascript
{
  "sudt": {
    "path": "built-in/sudt",
    // will be added to file after the deployment
    "cellDep": {
        "depType": "${code}",
        "outPoint": {
          "txHash": "${txHash}",
          "index": "0x0",
        },
      },
      "script": {
        "codeHash": "${codeHash}",
        "hashType": "data"
      }
}
```

**Comment by yanguoyu** [comment]
Should we need to consider how to deploy a contract that `depType` is `depGroup`, it may need to deploy twice, once to deploy the contract with code, and once to deploy reference of the code contract cell and other dep cells.

**Comment by Keith-CY** [comment]
> Should we need to consider how to deploy a contract that `depType` is `depGroup`, it may need to deploy twice, once to deploy the contract with code, and once to deploy reference of the code contract cell and other dep cells.

Please cover this in the contract deployment by kuai-cli @PainterPuppets

**Comment by Daryl-L** [comment]
> Should we need to consider how to deploy a contract that `depType` is `depGroup`, it may need to deploy twice, once to deploy the contract with code, and once to deploy reference of the code contract cell and other dep cells.

```javascript
{
  "sudt": {
    "path": "built-in/sudt",
    // will be added to file after the deployment
    "cellDep": {
      "depType": "code",
      "outPoint": {
        "txHash": "${txHash}",
        "index": "0x0"
      }
    },
    "script": {
      "codeHash": "${codeHash}",
      "hashType": "data"
    }
  },
  "custom": {
    "path": "custom",
    "cellDep": {
      "txHash": {
        "txHash": "${txHash}",
        "index": "0x0"
      },
      "depType": "depGroup",
      "cellDeps": [
        {
          "txHash": {
            "txHash": "${txHash}",
            "index": "0x0"
          }, 
          "depType": "code"
        }
      ]
    }
  }
}
```

Set deps while the dep type is dep group.

**Comment by Keith-CY** [comment]
> Another point, should we place the binary files into the repo? I think there are three ways to provide the built-in contracts
> 
> 1. place the binary files into the repo directly.
> 2. use submodule from [nervosnetwork/ckb-production-scripts](https://github.com/nervosnetwork/ckb-production-scripts), build the contracts when install `kuai`
> 3. developers clone the [nervosnetwork/ckb-production-scripts](https://github.com/nervosnetwork/ckb-production-scripts) and build the contracts themselves, place the path into config file which will be provided to the `kuai-cli` command
> 
> @Keith-CY @yanguoyu @zhangyouxin @PainterPuppets I prefer the first way.

Building on users' PC is unacceptable because it requires the setup of develop environment.

Another option is to build binaries by CI and publish them in an independent repo, as a git submodule of `kuai`

**Comment by homura** [comment]
Is this ticket already is in development? Maybe we can reuse the e2e node of Nexus's https://github.com/ckb-js/nexus/pull/239

**Comment by Keith-CY** [comment]
> Is this ticket already is in development? Maybe we can reuse the e2e node of Nexus's [ckb-js/nexus#239](https://github.com/ckb-js/nexus/pull/239)

We're still designing it. This topic has been discussed in discord channel and can be continued there because it covers not only these two projects. We can even propose a project for e2e test in various projects.

**Comment by homura** [comment]
There is a simple CKB wrapper is implemented in [Nexus](https://github.com/ckb-js/nexus/blob/main/e2e/README.md#start-a-e2e-node), with some [use cases](https://github.com/ckb-js/nexus/blob/081d634136a48a7bc5bb75900df7fd8603e6b722/e2e/tests/CkbNode.test.ts) like claiming devnet token from genesis UTxO

**Comment by Daryl-L** [comment]
> There is a simple CKB wrapper is implemented in [Nexus](https://github.com/ckb-js/nexus/blob/main/e2e/README.md#start-a-e2e-node), with some [use cases](https://github.com/ckb-js/nexus/blob/081d634136a48a7bc5bb75900df7fd8603e6b722/e2e/tests/CkbNode.test.ts) like claiming devnet token from genesis UTxO

So with this wrapper, we can run the dev node without docker, right?

**Comment by homura** [comment]
> So with this wrapper, we can run the dev node without docker, right?

You're right, the wrapper will

- download CKB if it is not downloaded
- run the CKB via an unused port

**Comment by Daryl-L** [comment]
> > So with this wrapper, we can run the dev node without docker, right?
> 
> You're right, the wrapper will
> 
> * download CKB if it is not downloaded
> * run the CKB via an unused port

I'll have a try in `kuai`

**Comment by Daryl-L** [comment]
I copied the code from nexus, and made some necessary modification, to instead of using docker node. And then I will create a repo to publish the binary files of built-in scripts for `kuai` to download. The binary files will be placed in OS cache directory as nexus did. Is that ok?

@Keith-CY @homura @yanguoyu @PainterPuppets @zhengjianhui 

The PR will be updated tomorrow after fully test.

**Comment by yanguoyu** [comment]
So we will not use docker to start ckb dev chain? But if we start `testnet` or `mainnet` we can still use docker?

**Comment by Keith-CY** [comment]
> So we will not use docker to start ckb dev chain? But if we start `testnet` or `mainnet` we can still use docker?

Any feedback from lumos users that complain about launching ckb node? @homura @zhangyouxin @PainterPuppets @IronLu233

**Comment by homura** [comment]
> Any feedback from lumos users that complain about launching ckb node?

Lumos will only launch a CKB node when run its E2E testing, so the users of Lumos do not need to install a Docker or CKB node

**Comment by Keith-CY** [comment]
> > Any feedback from lumos users that complain about launching ckb node?
> 
> Lumos will only launch a CKB node when run its E2E testing, so the users of Lumos do not need to install a Docker or CKB node

So we can assume that users of lumos can host their own node successfully.

But after consideration, I think it is necessary to use docker for the production environment because we may recommend users to deploy projects built by kuai via docker.

**Comment by Keith-CY** [comment]
PR: https://github.com/ckb-js/kuai/pull/257
