### ISSUE TITLE
Build a docs website for the project that build by kuai

### ISSUE THREAD

**Issue by yanguoyu** [ckb-js/kuai#244]
I will try to do this from the following steps:
1. Build a doc about how to run the project if some developers clone this project. This may be created from a template.
2. Build a doc about the exposed APIs for other DApp developers, this may be created from JSDoc or others tools.

@Keith-CY @Daryl-L @zhengjianhui @PainterPuppets Do you have any other additions?

**Comment by Daryl-L** [comment]
I think another thing we can tell developers is how to use the usage of kuai-cli

**Comment by Keith-CY** [comment]
> I think another thing we can tell developers is how to use the usage of kuai-cli

It should be included in https://github.com/ckb-js/kuai/issues/228 because this feature is to generate docs from projects built on kuai/kuai-cli, the document of users' projects.

The MVP is integrating **typedoc**(https://bestofjs.org/projects/typedoc) and providing an npm script to generate `typescript document`

**Comment by Keith-CY** [comment]
Another point I'd consider is how to deploy the document pages, a config should be included for github pages or vercel

**Comment by yanguoyu** [comment]
Typedoc is a good point to create an exposed interface doc for DApp. We only need to define some rules to generate docs.
If there are no more questions, I will try to start this. 
After finishing this, when developers create a project by `kuai`, It will create a `ReadMe.MD` which includes a simple introduction, and how to run this project and deploy it. And create a doc about this project which include `ReadMe.MD` and exposed interfaces. If developers change the `ReadMe.MD` or add exposed interfaces, they can rebuild the doc by `yarn doc`.

**Comment by Keith-CY** [comment]
> Typedoc is a good point to create an exposed interface doc for DApp. We only need to define some rules to generate docs. If there are no more questions, I will try to start this. After finishing this, when developers create a project by `kuai`, It will create a `ReadMe.MD` which includes a simple introduction, and how to run this project and deploy it. And create a doc about this project which include `ReadMe.MD` and exposed interfaces. If developers change the `ReadMe.MD` or add exposed interfaces, they can rebuild the doc by `yarn doc`.

Any plan on generating docs from module level? Say add a comment at the top of a file and will be extracted as the description of the module. Very similar to `//!` in rust docs(https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html)

**Comment by Keith-CY** [comment]
> > Typedoc is a good point to create an exposed interface doc for DApp. We only need to define some rules to generate docs. If there are no more questions, I will try to start this. After finishing this, when developers create a project by `kuai`, It will create a `ReadMe.MD` which includes a simple introduction, and how to run this project and deploy it. And create a doc about this project which include `ReadMe.MD` and exposed interfaces. If developers change the `ReadMe.MD` or add exposed interfaces, they can rebuild the doc by `yarn doc`.
> 
> Any plan on generating docs at module level? Say add a comment at the top of a file and will be extracted as the description of the module. Very similar to `//!` in rust docs([doc.rust-lang.org/rustdoc/how-to-write-documentation.html](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html))

It's already supported in typedoc
https://typedoc.org/tags/module/

**Comment by yanguoyu** [comment]
> > > Typedoc is a good point to create an exposed interface doc for DApp. We only need to define some rules to generate docs. If there are no more questions, I will try to start this. After finishing this, when developers create a project by `kuai`, It will create a `ReadMe.MD` which includes a simple introduction, and how to run this project and deploy it. And create a doc about this project which include `ReadMe.MD` and exposed interfaces. If developers change the `ReadMe.MD` or add exposed interfaces, they can rebuild the doc by `yarn doc`.
> > 
> > 
> > Any plan on generating docs at module level? Say add a comment at the top of a file and will be extracted as the description of the module. Very similar to `//!` in rust docs([doc.rust-lang.org/rustdoc/how-to-write-documentation.html](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html))
> 
> It's already supported in typedoc https://typedoc.org/tags/module/

I think we can output `@module` in the template project's module. And developers can refer to this or not.

**Comment by yanguoyu** [comment]
We will add `@module` in the template project's module. @Keith-CY 
And in the future, we will add a command to create a module that will include `@module` at the top of the file.

**Comment by yanguoyu** [comment]
https://github.com/ckb-js/kuai/pull/282

**Comment by Keith-CY** [comment]
> doc.rust-lang.org/rustdoc/how-to-write-documentation.html

Default `@module` in main modules of samples/mvp are added by https://github.com/ckb-js/kuai/pull/285
