### ISSUE TITLE
optimize kuai contract cli for support multisig easily

### ISSUE THREAD

**Issue by PainterPuppets** [ckb-js/kuai#276]
Currently kuai deployment contract only supports local signature deployment, which is a very bad experience when using multiple devices for multi-signature.
So in order to optimize the multi-signature experience and reduce the difficulty for users, we decided to change the current signature process of kuai cli transactions and add an import / export json function, which is compatible with ckb-cli. https://github.com/ckb-js/kuai/pull/267#issuecomment-1549312884

In order to do this kuai will also add a kuai tx cli, which will probably have the following subcommands, most of which will reuse the ckb-cli tx command when possible

 - kuai tx:generate-empty-tx
 - kuai tx:generate-deploy-tx
 - kuai tx:generate-upgrade-tx
 - kuai tx:pay-fee 
 - kuai tx:inject-capacity
 - kuai tx:add-input
 - kuai tx:add-output
 - kuai tx:add-signature
 - kuai tx:sign
 - kuai tx:add-multisig-config
 - kuai tx:get-signing-entries
 - kuai tx:parse
 - kuai tx:format
 - kuai tx:send

With the addition of these subcommands, the flow of the kuai deployment contract will look like this

Compile：
```bash
# name is optional, when it is not, all contracts in the working directory will be built
> kuai contract build --name <name> --release
```

Deployment
```bash
# generate deploy tx
# kuai will generate a json file compatible with the ckb-cli tx command, where name and binPath can be passed in, the from part can be filled in with an address or a multisig config, and the --typeid identifier is whether the contract has been deployed in typid mode
> kuai contract deploy --name <name> --binPath <binPath> --from <address or [multisig, r, n, hashs…]> --typeid --export ./tx.json
# signing
# 1. sign with ckb-cli
> ckb-cli tx sign-inputs --from-account xxx --tx-file <tx-file>
# 2. custom process signing
# we learned that the signature method of .bit is to send the message to a slack, sign the message and then upload the signature. kuai provides some hook injection points that can be used to generate the message to be signed and trigger webhook and other operations. After collecting the signature, use ckb-cli to add the signature
> ckb-cli tx add-signature --lock-args <lock-args> --signature <signature> --tx-file <tx-file>
# send tx
> ckb-cli tx send --tx-file <tx-file>
```

Upgrade
```bash
# generate upgrade tx
# typeIdArgs is used to find the latest cell of the contract that uses the typeid, payer is the account that pays the fee and the spread, you can fill in an address or a multisig config
> kuai contract upgrade --name <name> --binPath <binPath> --typeIdArgs xxx --payer xxx --export ./tx.json
#  signing and sent parts are the same as deployed above
```

The @ link of .bit team suggested some changes, about these four points

1. kuai cli currently uses camel naming for args, while cli projects are more common in the form of snake cases
2. the use of typeid when deploying the contract should be the recommended practice, if there are special needs should be added --no-type-id parameter
3. the --from parameter of kuai contract deploy is a bit unclear whether it is the fee payment address or the contract holding address, these two addresses should be split up into --payer and --to.
4. the typeIdArgs parameter can be obtained from the chain or local migration information file, kuai does not do this in the end is that the user also has to wrap a shell or something.

The fourth point requires kuai to maintain an additional migration file, which feels a bit trivial. A simpler way is to add a --migrations parameter to the kuai contract upgrade command as ckb-cli compatibility, so that other commands can be used without introducing migration for the time being to reduce the Mental burden

I don't see any problem with the other points, and will modify them in the pr afterwards

**Comment by Keith-CY** [comment]
Partially implemented by https://github.com/ckb-js/kuai/pull/302
