### ISSUE TITLE
Store models are not bound automatically in mvp

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#278]
The subscription to store models are implemented by `auto bind` at https://github.com/ckb-js/kuai/blob/develop/packages/samples/mvp-dapp/src/app.controller.ts#L51

There will be two `load` calls:
1. The first one registers `store model` so lumos will fetch cells for it;
2. The second one load unmarshals `data` from the collected cells.

So the responses are expected to be `404: not found` and `200: data`

During the interaction with MVP at commit `c5fc2b8fed5b8dd2f4b732faa2c07a257cc3ab62`, the response of `load` is always `404: not found`, which means the `auto bind` does not work properly.

**Comment by Daryl-L** [comment]
> The subscription to store models are implemented by `auto bind` at https://github.com/ckb-js/kuai/blob/develop/packages/samples/mvp-dapp/src/app.controller.ts#L51
> 
> There will be two `load` calls:
> 
> 1. The first one registers `store model` so lumos will fetch cells for it;
> 2. The second one load unmarshals `data` from the collected cells.
> 
> So the responses are expected to be `404: not found` and `200: data`
> 
> During the interaction with MVP at commit `c5fc2b8fed5b8dd2f4b732faa2c07a257cc3ab62`, the response of `load` is always `404: not found`, which means the `auto bind` does not work properly.

After trying several times, I didn't see the response always be `404`. Maybe the account doesn't have the data?

**Comment by Keith-CY** [comment]
> > The subscription to store models are implemented by `auto bind` at [`develop`/packages/samples/mvp-dapp/src/app.controller.ts#L51](https://github.com/ckb-js/kuai/blob/develop/packages/samples/mvp-dapp/src/app.controller.ts?rgh-link-date=2023-05-31T05%3A14%3A23Z#L51)
> > There will be two `load` calls:
> > 
> > 1. The first one registers `store model` so lumos will fetch cells for it;
> > 2. The second one load unmarshals `data` from the collected cells.
> > 
> > So the responses are expected to be `404: not found` and `200: data`
> > During the interaction with MVP at commit `c5fc2b8fed5b8dd2f4b732faa2c07a257cc3ab62`, the response of `load` is always `404: not found`, which means the `auto bind` does not work properly.
> 
> After trying several times, I didn't see the response always be `404`. Maybe the account doesn't have the data?

I was trying with a fresh new address, with an amount claimed from the faucet, so the data doesn't exist.

But this API doesn't rely on on-chain data
1. on the first call, it registers `address` in `chain source` to filter cells, and return `404`
2. on the second call, it should return an empty `store` because cells should be cached in the `chain source`

But each call returned `404` as I opened this issue

**Comment by Keith-CY** [comment]
It's not caused by `auto bind`.

The underlying issue is that the `omnilock` configuration cannot be imported because `user config` is ignored on runtime and the network is always treated as `devnet`. `Omnilock` is unavailable on `devnet`.

```
Registry `find` catch error Error: OMNILOCK doesn't exist in ScriptRegistry
```

So the data cannot be collected from the indexer.

It has been fixed by https://github.com/ckb-js/kuai/pull/288
