### ISSUE TITLE
API of `autoBind` in `ActorProvider` is not configured correctly in project template

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#279]
Definition at https://github.com/ckb-js/kuai/blob/c5fc2b8fed5b8dd2f4b732faa2c07a257cc3ab62/packages/models/src/utils/decorator/provider.ts#L20-L23

The API call in project template https://github.com/ckb-js/kuai/blob/c5fc2b8fed5b8dd2f4b732faa2c07a257cc3ab62/packages/core/sample-projects/src/actors/app.ts#L12

**Comment by yanguoyu** [comment]
I'm editing `sample-projects` to add `typedoc`, so I will fix it at the same time.
