### ISSUE TITLE
Show all the options when run `kuai init`

### ISSUE THREAD

**Issue by yanguoyu** [ckb-js/kuai#281]
Now, when we run `kuai init` after we confirm one option, and then it will show the next option.
We can show all of the options after `kuai init`.
Like this
```bash
? Kuai project root: · /kuai/packages/samples
? Do you want to add a .gitignore? (Y/n) · true
? other options? (Y/n) › true
? other options? (Y/n) › true
```

**Comment by Keith-CY** [comment]
It would be clear for usage

**Comment by yanguoyu** [comment]
Sorry, I cannot find any CLI tools that can show all of the options, we can only suggest listing the options one by one at the beginning, but not giving an option after the init is starting.
