### ISSUE TITLE
Define JSON standard for json-storage and contract

### ISSUE THREAD

**Issue by yanguoyu** [ckb-js/kuai#307]
For support [BigNumber](https://www.npmjs.com/package/bignumber.js), I defined `replacer` and `reviver` for `JSON.stringify` and `JSON.parse`, but I forgot to consider how to deserialize these in contract with rust.

In order to keep unified standards for JSON with `kuai` and `contract`, we should define which types can use in JSON and how to serialize and deserialize them.
If we only support simple type maybe we only need to give an example, but if we support complex type(BigNumber), we may need to export a rust SDK to deserialize the hex string to a struct.

@zhengjianhui How do you think?

**Comment by yanguoyu** [comment]
We will remove support `BigNumber`, `json-storage` will only support `string` in simple types.

**Comment by zhengjianhui** [comment]
> 

It is recommended to use hex

**Comment by zhengjianhui** [comment]
> For support [BigNumber](https://www.npmjs.com/package/bignumber.js), I defined `replacer` and `reviver` for `JSON.stringify` and `JSON.parse`, but I forgot to consider how to deserialize these in contract with rust.
> 
> In order to keep unified standards for JSON with `kuai` and `contract`, we should define which types can use in JSON and how to serialize and deserialize them. If we only support simple type maybe we only need to give an example, but if we support complex type(BigNumber), we may need to export a rust SDK to deserialize the hex string to a struct.
> 
> @zhengjianhui How do you think?

It is recommended to use hex
