### ISSUE TITLE
It might not be able to use kuai to start a node on Apple M chip platform

### ISSUE THREAD

**Issue by Daryl-L** [ckb-js/kuai#312]
I have learnt from Acceptance that the ckb could not run in docker with Apple M1, as the kuai is using docker to start a node, so it is not supported.

**Comment by Keith-CY** [comment]
> I have learnt from Acceptance that the ckb could not run in docker with Apple M1, as the kuai is using docker to start a node, so it is not supported.

I'll check it with the core team for a solution

**Comment by Keith-CY** [comment]
Error Message

```bash
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)

Error: read ETIMEDOUT
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'read'
}
```

**Comment by Keith-CY** [comment]
Check with the core team how long it will take

**Comment by Daryl-L** [comment]
#319
