### ISSUE TITLE
Host the MVP dapp on https://railway.app/ for onboarding

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#330]
https://railway.app/ is the cloud platform to host services. The complexity of onboarding should be reduced by migrating the MVP demo to an easy-to-deploy platform so everyone can deploy their own demo, similar to why we deploy demo UI on vercel.

**Comment by yanguoyu** [comment]
https://railway.app/button This page can create a template to deploy for `railway`.
And `railway` support using `Dockerfile ` to deploy. I will try with `Dockerfile` to create a template button.

**Comment by yanguoyu** [comment]
To connect the `railway` Redis, we should add an option when connecting Redis. https://github.com/ckb-js/kuai/pull/402
