### ISSUE TITLE
Support caching and loading deployment information of contracts

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#334]
Now there's a convention in the MVP DApp tutorial, as mentioned at https://github.com/ckb-js/kuai/issues/306

> The deployment information should be generated automatically as a facility for the backend. It will be implemented soon, now we have to set it manually at `profile/contract/deployed/contracts.json`.

> The deployment information of the online demo can be found at [ebffba1/packages/samples/mvp-dapp/contract/deployed_demo](https://github.com/ckb-js/kuai/tree/ebffba1bc73255fa3ccf6d85300129c70bf88f47/packages/samples/mvp-dapp/contract/deployed_demo)

With this convention, the deployed contracts can be referenced by `getDeployedContracts`(https://github.com/ckb-js/kuai/blob/develop/packages/samples/mvp-dapp/src/utils/index.ts#L5-L23) for `Pattern` and `Transaction View`.

It would be great to inject the deployment information of contracts into runtime/pipeline automatically to reduce the mental burden of referencing contracts.

For this purpose, I would suggest that the deployment information should be generated by `kuai contract command` in a similar format as @Daryl-L designed at https://github.com/ckb-js/kuai/issues/235#issuecomment-1519093262 at a specific path, and an internal utility function should be exposed to loading deployment information for application runtime, and pipeline of the task system(https://github.com/ckb-js/kuai/issues/13). The utility function could be designed in the `contract model`(https://github.com/ckb-js/kuai/blob/develop/packages/models/src/contract/contract.ts)

Is this feature feasible and helpful to developers? @Daryl-L @PainterPuppets @yanguoyu

**Comment by yanguoyu** [comment]
It would be better if we can output the contract information when using `kuai contract deploy`.
IMO, we can expose the loading contract utils for developers, but it's unnecessary to load at runtime, it can be decided by developers.

**Comment by Keith-CY** [comment]
> It would be better if we can output the contract information when using `kuai contract deploy`. IMO, we can expose the loading contract utils for developers, but it's unnecessary to load at runtime, it can be decided by developers.

Outputing deployment information along with `kuai contract deploy` is a good idea.

But what's the drawback of loading contracts automatically?

**Comment by PainterPuppets** [comment]
We currently have a migration file, so maybe we could use the migration file for this configuration?

Migration file look like that
```json
{
  "cell_recipes": [
    {
      "name": "sample-dapp",
      "tx_hash": "0xf9ce0227ac1e76cb88c89ac4db349ea3cdc684f697819fe0f767b9fcf7ffd4ef",
      "index": 0,
      "occupied_capacity": 0,
      "data_hash": "0xf15cc653723ea85edbd6bebec5c3df5197ce0067f7d0b87e6ed78fd8cd626265",
      "type_id": "0xf15cc653723ea85edbd6bebec5c3df5197ce0067f7d0b87e6ed78fd8cd626265"
    }
  ]
}
```

**Comment by Daryl-L** [comment]
https://github.com/ckb-js/kuai/issues/235#issuecomment-1519093262

**Comment by Keith-CY** [comment]
> #235 (comment)

The fields mentioned in the comment and [deployed_demo](https://github.com/ckb-js/kuai/blob/develop/packages/samples/mvp-dapp/contract/deployed_demo/contracts.json) are as follows

- name: contract name
- path: the path to the binary
- cellDep: reference info in a transaction when the contract is used
	- depType
	- outPoint
		- txHash
		- index
- script
	- codeHash: code hash of the contract, used in the pattern/filter of a model to gather cells
	- hashType: hash type of the contract, used in the pattern/filter of a model to gather cells

**Comment by Keith-CY** [comment]
> > #235 (comment)
> 
> The fields mentioned in the comment and [deployed_demo](https://github.com/ckb-js/kuai/blob/develop/packages/samples/mvp-dapp/contract/deployed_demo/contracts.json?rgh-link-date=2023-07-18T05%3A49%3A39Z) are as follows
> 
> * name: contract name
> * path: the path to the binary
> * cellDep: reference info in a transaction when the contract is used
>   
>   * depType
>   * outPoint
>     
>     * txHash
>     * index
> * script
>   
>   * codeHash: code hash of the contract, used in the pattern/filter of a model to gather cells
>   * hashType: hash type of the contract, used in the pattern/filter of a model to gather cells

The deployment configurations for preset on devnet and reference in the backend are almost the same, except that format is slightly different.

So here, I would suggest unifying them into the following format.

```ts
interface ContractDeploymentInfo {
  name: string // contract name, used as the index of the contract
  path?: string // relative path to the binary
  cellDep: {
    depType: 'code' | 'depGroup'
    outPoint: Record<'txHash' | 'index', string>
  }
  scriptBase: { // it's named `scriptBase` but not `script` because it lacks `args`
    codeHash: string
    hashType: 'data' | 'type'
  }
}
```

The default path to the deployment info for the backend is `contract_module/deployed/contract.json`

And a utility module will be delivered in the project, which loads the deployment information on launch, and exposes a method to get a specified contract

```ts
interface ContractUtility {
  private contractList: Map<string, ContractDeploymentInfo>
  public load(directory: string): void
  public get(name: string): ContractDeploymentInfo | null
}
```

**Comment by PainterPuppets** [comment]
Looks great!
I have an idea: contract management & contract loader could be layerd, so that kuai not only provide an conventional storage method but also have more extensibility.

It might look something like this:

```ts
interface ContractManager {
	contracts: ContractDeploymentInfo[]
	loaders: ContractLoader[]
}

Interface ContractLoader {
	load: () => ContractDeploymentInfo[]
}
```

**Comment by Daryl-L** [comment]
> > > #235 (comment)
> > 
> > 
> > The fields mentioned in the comment and [deployed_demo](https://github.com/ckb-js/kuai/blob/develop/packages/samples/mvp-dapp/contract/deployed_demo/contracts.json?rgh-link-date=2023-07-18T05%3A49%3A39Z) are as follows
> > 
> > * name: contract name
> > * path: the path to the binary
> > * cellDep: reference info in a transaction when the contract is used
> >   
> >   * depType
> >   * outPoint
> >     
> >     * txHash
> >     * index
> > * script
> >   
> >   * codeHash: code hash of the contract, used in the pattern/filter of a model to gather cells
> >   * hashType: hash type of the contract, used in the pattern/filter of a model to gather cells
> 
> The deployment configurations for preset on devnet and reference in the backend are almost the same, except that format is slightly different.
> 
> So here, I would suggest unifying them into the following format.
> 
> ```ts
> interface ContractDeploymentInfo {
>   name: string // contract name, used as the index of the contract
>   path?: string // relative path to the binary
>   cellDep: {
>     depType: 'code' | 'depGroup'
>     outPoint: Record<'txHash' | 'index', string>
>   }
>   scriptBase: { // it's named `scriptBase` but not `script` because it lacks `args`
>     codeHash: string
>     hashType: 'data' | 'type'
>   }
> }
> ```
> 
> The default path to the deployment info for the backend is `contract_module/deployed/contract.json`
> 
> And a utility module will be delivered in the project, which loads the deployment information on launch, and exposes a method to get a specified contract
> 
> ```ts
> interface ContractUtility {
>   private contractList: Map<string, ContractDeploymentInfo>
>   public load(directory: string): void
>   public get(name: string): ContractDeploymentInfo | null
> }
> ```

Something about the binary path, I think maybe using array is much better for group of binary to deploy.

**Comment by Keith-CY** [comment]
> Looks great!
> 
> I have an idea: contract management & contract loader could be layerd, so that kuai not only provide an conventional storage method but also have more extensibility.
> 
> It might look something like this:
> 
> ```ts
> interface ContractManager {
> 	contracts: ContractDeploymentInfo[]
> 	loaders: ContractLoader[]
> }
> 
> interface ContractLoader {
> 	load: () => ContractDeploymentInfo[]
> }
> ```
> 
> And the default loader concrete maybe look like that
> 
> ```ts
> class KuaiContractLoader implements ContractLoader {
>     constructor(directory: string) {
>       ...
>     }
> 
>     load() {
>       ...
>     }
> }
> ```

LGTM

**Comment by Keith-CY** [comment]
> > > > #235 (comment)
> > > 
> > > 
> > > The fields mentioned in the comment and [deployed_demo](https://github.com/ckb-js/kuai/blob/develop/packages/samples/mvp-dapp/contract/deployed_demo/contracts.json?rgh-link-date=2023-07-20T01%3A20%3A37Z) are as follows
> > > 
> > > * name: contract name
> > > * path: the path to the binary
> > > * cellDep: reference info in a transaction when the contract is used
> > >   
> > >   * depType
> > >   * outPoint
> > >     
> > >     * txHash
> > >     * index
> > > * script
> > >   
> > >   * codeHash: code hash of the contract, used in the pattern/filter of a model to gather cells
> > >   * hashType: hash type of the contract, used in the pattern/filter of a model to gather cells
> > 
> > 
> > The deployment configurations for preset on devnet and reference in the backend are almost the same, except that format is slightly different.
> > So here, I would suggest unifying them into the following format.
> > ```ts
> > interface ContractDeploymentInfo {
> >   name: string // contract name, used as the index of the contract
> >   path?: string // relative path to the binary
> >   cellDep: {
> >     depType: 'code' | 'depGroup'
> >     outPoint: Record<'txHash' | 'index', string>
> >   }
> >   scriptBase: { // it's named `scriptBase` but not `script` because it lacks `args`
> >     codeHash: string
> >     hashType: 'data' | 'type'
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The default path to the deployment info for the backend is `contract_module/deployed/contract.json`
> > And a utility module will be delivered in the project, which loads the deployment information on launch, and exposes a method to get a specified contract
> > ```ts
> > interface ContractUtility {
> >   private contractList: Map<string, ContractDeploymentInfo>
> >   public load(directory: string): void
> >   public get(name: string): ContractDeploymentInfo | null
> > }
> > ```
> 
> Something about the binary path, I think maybe using array is much better for group of binaries to deploy.

Make sense.

I have a question when mentioning the group of contract binary.
Is it possible to output metadata of the contracts binaries to deploy, similar to the dependencies lock file

```
    "profile": {
      "name": "kuai-project",
      "resolved": "~/build/profile",
      "dependencies": {
        "koa": "2.14.1",
      },
    },
    "koa": {
      "version": "2.14.2",
      "resolved": "~/build/koa",
      "integrity": "sha512-VFI2bpJaodz6P7x2uyLiX6RLYpZmOJqNmoCst/Yyd7hQlszyPwG/I9CQJ63nOtKSxpt5M7NH67V6nJL2BwCl7g==",
    },
```

If it is possible, the link could be pointed to the metadata

**Comment by Keith-CY** [comment]
If there are no more discussions, this feature will be implemented by generating `contracts.json` at the specified path, and loading them on mount

**Comment by Daryl-L** [comment]
I would like to change the `ContractDeploymentInfo` to as follows:

```typescript
interface ContractDeploymentInfo {
  name: string // contract name, used as the index of the contract
  path?: string // relative path to the binary
  cellDeps?: {
    name?: string,
    cellDeps?: {
      depType: 'code' | 'depGroup'
      outPoint: Record<'txHash' | 'index', string>
    }
  }[]
  depType: 'code' | 'depGroup'
  outPoint: Record<'txHash' | 'index', string>
  scriptBase: { // it's named `scriptBase` but not `script` because it lacks `args`
    codeHash: string
    hashType: 'data' | 'type'
  }
}
```

In this structure, I change the `path` back to string, and add the `cellDeps` for the group of binaries to deploy. Developers should add the name and path one by one to deploy, with the cellDep which is deployed before.

**Comment by Keith-CY** [comment]
> I would like to change the `ContractDeploymentInfo` to as follows:
> 
> ```ts
> interface ContractDeploymentInfo {
>   name: string // contract name, used as the index of the contract
>   path?: string // relative path to the binary
>   cellDeps?: {
>     name?: string,
>     cellDeps?: {
>       depType: 'code' | 'depGroup'
>       outPoint: Record<'txHash' | 'index', string>
>     }
>   }[]
>   depType: 'code' | 'depGroup'
>   outPoint: Record<'txHash' | 'index', string>
>   scriptBase: { // it's named `scriptBase` but not `script` because it lacks `args`
>     codeHash: string
>     hashType: 'data' | 'type'
>   }
> }
> ```
> 
> In this structure, I change the `path` back to string, and add the `cellDeps` for the group of binaries to deploy. Developers should add the name and path one by one to deploy, with the cellDep which is deployed before.

I was impressed that I asked about what does `cellDeps.cellDeps` do, but I still lost it.

**Comment by Daryl-L** [comment]
> > I would like to change the `ContractDeploymentInfo` to as follows:
> > ```ts
> > interface ContractDeploymentInfo {
> >   name: string // contract name, used as the index of the contract
> >   path?: string // relative path to the binary
> >   cellDeps?: {
> >     name?: string,
> >     cellDeps?: {
> >       depType: 'code' | 'depGroup'
> >       outPoint: Record<'txHash' | 'index', string>
> >     }
> >   }[]
> >   depType: 'code' | 'depGroup'
> >   outPoint: Record<'txHash' | 'index', string>
> >   scriptBase: { // it's named `scriptBase` but not `script` because it lacks `args`
> >     codeHash: string
> >     hashType: 'data' | 'type'
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this structure, I change the `path` back to string, and add the `cellDeps` for the group of binaries to deploy. Developers should add the name and path one by one to deploy, with the cellDep which is deployed before.
> 
> I was impressed that I asked about what does `cellDeps.cellDeps` do, but I still lost it.

Oops, the `cellDeps.cellDeps` should be `cellDeps.cellDep`, it records the `cellDeps` for deployment.

For example, if there are 3 binaries to deploy, and the first two binaries is for the last one to depend, the object maybe like this.

```javascript
[
  {
    "name": "1",
    "path": "contract/1",
    "depType": "code",
    "outPoint": "0x",
    "scriptBase": {
      "codeHash": "0x",
      "hashType": "type"
    }
  },
  {
    "name": "2",
    "path": "contract/2",
    "depType": "code",
    "outPoint": "0x",
    "scriptBase": {
      "codeHash": "0x",
      "hashType": "type"
    }
  },
  {
    "name": "3",
    "path": "contract/3",
    "depType": "code",
    "outPoint": "0x",
    "cellDeps": [
      {
        "name": "1",
        // cellDep will be filled after the first two being deployed
      }
    ],
    "scriptBase": {
      "codeHash": "0x",
      "hashType": "type"
    }
  }
]
```

The three will be deployed one by one.

**Comment by Keith-CY** [comment]
> > > I would like to change the `ContractDeploymentInfo` to as follows:
> > > ```ts
> > > interface ContractDeploymentInfo {
> > >   name: string // contract name, used as the index of the contract
> > >   path?: string // relative path to the binary
> > >   cellDeps?: {
> > >     name?: string,
> > >     cellDeps?: {
> > >       depType: 'code' | 'depGroup'
> > >       outPoint: Record<'txHash' | 'index', string>
> > >     }
> > >   }[]
> > >   depType: 'code' | 'depGroup'
> > >   outPoint: Record<'txHash' | 'index', string>
> > >   scriptBase: { // it's named `scriptBase` but not `script` because it lacks `args`
> > >     codeHash: string
> > >     hashType: 'data' | 'type'
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In this structure, I change the `path` back to string, and add the `cellDeps` for the group of binaries to deploy. Developers should add the name and path one by one to deploy, with the cellDep which is deployed before.
> > 
> > 
> > I was impressed that I asked about what does `cellDeps.cellDeps` do, but I still lost it.
> 
> Oops, the `cellDeps.cellDeps` should be `cellDeps.cellDep`, it records the `cellDeps` for deployment.
> 
> For example, if there are 3 binaries to deploy, and the first two binaries is for the last one to depend, the object maybe like this.
> 
> ```js
> [
>   {
>     "name": "1",
>     "path": "contract/1",
>     "depType": "code",
>     "outPoint": "0x",
>     "scriptBase": {
>       "codeHash": "0x",
>       "hashType": "type"
>     }
>   },
>   {
>     "name": "2",
>     "path": "contract/2",
>     "depType": "code",
>     "outPoint": "0x",
>     "scriptBase": {
>       "codeHash": "0x",
>       "hashType": "type"
>     }
>   },
>   {
>     "name": "3",
>     "path": "contract/3",
>     "depType": "code",
>     "outPoint": "0x",
>     "cellDeps": [
>       {
>         "name": "1",
>         // cellDep will be filled after the first two being deployed
>       }
>     ],
>     "scriptBase": {
>       "codeHash": "0x",
>       "hashType": "type"
>     }
>   }
> ]
> ```
> 
> The three will be deployed one by one.

I've 2 questions

1. This configuration is used as deployed information for backend to reference the contract, is deployment dependency necessary to be included?
2. The tree structure is redundant, `3.cellDeps` can point to `1` and `2` directly, and load `1.outPoint`, `2.outPoint` dynamically.

**Comment by Daryl-L** [comment]
I have changed the ContractDeploymentInfo to as follows:

```typescript
interface ContractDeploymentInfo {
  name: string // contract name, used as the index of the contract
  path?: string // relative path to the binary
  cellDeps?: {
    name?: string,
    cellDep?: {
      depType: 'code' | 'depGroup'
      outPoint: Record<'txHash' | 'index', string>
    }
  }[]
  depType: 'code' | 'depGroup'
  outPoint: Record<'txHash' | 'index', string>
  scriptBase: { // it's named `scriptBase` but not `script` because it lacks `args`
    codeHash: string
    hashType: 'data' | 'type'
  }
}
```

In my opinion, for developers to use, they should prepare a partial configuration before.

**`name` is required for each contract config.**

The `cellDeps` is optional. There are two cases that developers should provider.

First case, there are multiple binaries to deploy. In this case, the `cellDep` in the item of `cellDeps` is optional, and the `name` is required, and the value is the name of which the contract depends. Notice, in this case, the dependencies **must be** in front of this contract.

Here is the example.

```javascript
[
  {
    "name": "1",
    "path": "contract/1",
    "depType": "code",
    "outPoint": "0x",
    "scriptBase": {
      "codeHash": "0x",
      "hashType": "type"
    }
  },
  {
    "name": "2",
    "path": "contract/2",
    "depType": "code",
    "outPoint": "0x",
    "scriptBase": {
      "codeHash": "0x",
      "hashType": "type"
    }
  },
  {
    "name": "3",
    "path": "contract/3",
    "depType": "depGroup",
    "outPoint": "0x",
    "cellDeps": [
      {
        "name": "1",
        // cellDep will be filled after the first two being deployed
      }
    ],
    "scriptBase": {
      "codeHash": "0x",
      "hashType": "type"
    }
  }
]
```

Second case, if the dependencies have been already deployed, like the `omnilock` and so on, the `name` is optional, and the `cellDep` is required.

**Comment by Daryl-L** [comment]
> Looks great!
> 
> I have an idea: contract management & contract loader could be layerd, so that kuai not only provide an conventional storage method but also have more extensibility.
> 
> It might look something like this:
> 
> ```ts
> interface ContractManager {
> 	contracts: ContractDeploymentInfo[]
> 	loaders: ContractLoader[]
> }
> 
> interface ContractLoader {
> 	load: () => ContractDeploymentInfo[]
> }
> ```
> 
> And the default loader concrete maybe look like that
> 
> ```ts
> class KuaiContractLoader implements ContractLoader {
>     constructor(directory: string) {
>       ...
>     }
> 
>     load() {
>       ...
>     }
> }
> ```

One more question, why should we extract `loader` here, will be multiple kinds of `loader` in the future?

**Comment by Keith-CY** [comment]
> > Looks great!
> > I have an idea: contract management & contract loader could be layerd, so that kuai not only provide an conventional storage method but also have more extensibility.
> > It might look something like this:
> > ```ts
> > interface ContractManager {
> > 	contracts: ContractDeploymentInfo[]
> > 	loaders: ContractLoader[]
> > }
> > 
> > interface ContractLoader {
> > 	load: () => ContractDeploymentInfo[]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the default loader concrete maybe look like that
> > ```ts
> > class KuaiContractLoader implements ContractLoader {
> >     constructor(directory: string) {
> >       ...
> >     }
> > 
> >     load() {
> >       ...
> >     }
> > }
> > ```
> 
> One more question, why should we extract `loader` here, will be multiple kinds of `loader` in the future?

`Supporting more kinds of loader` is one benefit it brings. I will treat `separating contract manager and contract loader` as control of inversion to make the logic clear and independent.

**Comment by yanguoyu** [comment]
Does `cellDeps` will include one of the `name` or `cellDep` properties? Maybe this is more clear.
```typescript
interface ContractDeploymentInfo {
  name: string // contract name, used as the index of the contract
  path?: string // relative path to the binary
  cellDeps?: ({
    name: string,
  } | cellDep: {
      depType: 'code' | 'depGroup'
      outPoint: Record<'txHash' | 'index', string>
  })[]
  //...
}
```

**Comment by Daryl-L** [comment]
> Does `cellDeps` will include one of the `name` or `cellDep` properties? Maybe this is more clear.
> 
> ```ts
> interface ContractDeploymentInfo {
>   name: string // contract name, used as the index of the contract
>   path?: string // relative path to the binary
>   cellDeps?: ({
>     name: string,
>   } | cellDep: {
>       depType: 'code' | 'depGroup'
>       outPoint: Record<'txHash' | 'index', string>
>   })[]
>   //...
> }
> ```

Looks great, I will change like this.

**Comment by Keith-CY** [comment]
PR: https://github.com/ckb-js/kuai/pull/425
