### ISSUE TITLE
Version numbers in mvp and project template are not covered by lerna

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#388]
Ref: https://github.com/ckb-js/kuai/commit/05a5fe032f02a9b72eeebe54757d72ec4b5aa382

**Comment by Keith-CY** [comment]
Bumping of linked dependencies of `samples/*` should be fixed by https://github.com/ckb-js/kuai/pull/397

**Comment by PainterPuppets** [comment]
I have two ideas for updating template versions

1. use the version field in lerna.json, and after each bump-version will actively change the field according to the version in lerna.json.

The downside might be some version we don't want the template to be upgraded to, like alpha/nightly.

2. Use npm tag, change the downloaded version in template to latest or a specific tag, when kuai is published to npm, these tags will be changed synchronously, and the latest version will be downloaded when template is used to download.

The downside is publishing to npm.

**Comment by Keith-CY** [comment]
> The downside might be some version we don't want the template to be upgraded to, like alpha/nightly.

I have a question and a solution about this downside

question: in what case won't we use the paired versions, like `kuai-cli@v0.0.2-alpha` inits a project using `kuai@v0.0.1`

solution: the version bumping can be done by `postversion` hook with a custom script to ignore ignore `alpha/nightly` updates.

Ref:
postversion: https://docs.npmjs.com/cli/v9/commands/npm-version

**Comment by PainterPuppets** [comment]
> > The downside might be some version we don't want the template to be upgraded to, like alpha/nightly.
> 
> I have a question and a solution about this downside
> 
> question: in what case won't we use the paired versions, like `kuai-cli@v0.0.2-alpha` inits a project using `kuai@v0.0.1`
> 
> solution: the version bumping can be done by `postversion` hook with a custom script to ignore ignore `alpha/nightly` updates.
> 
> Ref: postversion: https://docs.npmjs.com/cli/v9/commands/npm-version

It's possible that some new versions of kuai offer experimental features that are added to templates after a certain degree of stable operation, but of course that probably won't be the case for the most part, it just a preconception and may depend largely on our upgrade strategy

And so our implementation would be to change the version number in the template in the `postbump-version` hook?

**Comment by Keith-CY** [comment]
> It's possible that some new versions of kuai offer experimental features that are added to templates after a certain degree of stable operation, but of course that probably won't be the case for the most part, it just a preconception and may depend largely on our upgrade strategy

I think it's reasonable to deliver `experimental` features by `kuai-cli` marked `experimental`.

> And so our implementation would be to change the version number in the template in the `postbump-version` hook?

`bump-version` calls `npm run version` and `npm run postversion`, invoking the custom script by `npm run postversion` should work

**Comment by Keith-CY** [comment]
Will be fixed by https://github.com/ckb-js/kuai/pull/395
