### ISSUE TITLE
Failed to create new contract in the new project created by kuai init

### ISSUE THREAD

**Issue by doitian** [ckb-js/kuai#486]
```
$ kuai contract new --name hello
New contract "hello"
error: No such file or directory (os error 2)
Error: Command failed: cd /home/ian/codebase/kuai-hello-dapp/contract && capsule new-contract hello --template rust
```

Fixed by creating the directory contract/contracts manually

**Comment by Keith-CY** [comment]
Please have a check @PainterPuppets

**Comment by PainterPuppets** [comment]
It looks like the` capsule` is not initialized, which may occur because the project was not created via `kuai-cli init`

Submitted a pr to optimize this process, so that if the `capsule` is not initialized, it will be initialized automatically.

https://github.com/ckb-js/kuai/pull/489
