### ISSUE TITLE
Some problem in developing the sUDT manager

### ISSUE THREAD

**Issue by Daryl-L** [ckb-js/kuai#504]
1. The consideration for transaction information was overlooked. In the development of the sUDT management platform, a requirement arose to manage the transaction history, necessitating the synchronization of on-chain transactions. However, within Kuai, there is no built-in functionality for syncing transactions. Consequently, it becomes necessary to independently implement the synchronization of transaction records in the script and store them in the database.

2. The development experience with Kuai and Lumos in tandem is quite problematic. Take, for example, the generation of an sUDT, where Lumos provides the function `issueToken`. However, this function lacks the capability to pass cell information as the issuer. This renders the cell information synchronized by Kuai somewhat redundant. Regardless of whether Kuai provides cell information in the Model, Lumos needs to re-query through script or other account data, such as the `payFee` function. To enhance the Kuai development experience, it is essential for Lumos, as a framework for Nervos, to make certain adaptations.

**Comment by Daryl-L** [comment]
3. `Model` for `typescript` is strange too. Developers may have no idea to use `Model` to present the `type`, because each `Model` should have a `lock`. For example, if I want to collect how many holders of this token, I have no idea to achieve by `Kuai`.

**Comment by yanguoyu** [comment]
> 3\. because each `Model` should have a `lock`

I don't know why each `Model` should have a `lock`?

**Comment by Daryl-L** [comment]
> > 3. because each `Model` should have a `lock`
> 
> I don't know why each `Model` should have a `lock`?

Because the Resource Binding uses the lockHash to index the cell
