### ISSUE TITLE
Add a mvp dapp to verify the functions of kuai

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/kuai#54]
The .bit project currently has four main features

.bit Alias: https://docs.did.id/developers/dotbit-alias
.bit Namespaces: https://docs.did.id/developers/records-key-namespace
.bit schemas: https://github.com/dotbitHQ/das-types/tree/master/schemas
subDID: https://www.did.id/subdid

General docs: https://github.com/dotbitHQ/das-contracts/tree/master/docs

---

At the stage of MVP, we need to verify whether the capacity abstraction provided by `kuai` can satisfy the DApp design, i.e., if the developer could **add**, **delete**, **modify**, and **read** cells of the dapp solely by `Store`. Thus we choose the `namespace` feature as the main function of the MVP DApp.

The detail of `namespace` could be found in .bit document(https://docs.did.id/developers/records-key-namespace), while its schema can be found at https://github.com/dotbitHQ/das-types/blob/master/schemas/cell.mol#L263-L277 

```mermaid
flowchart TD
    input([Input]) --> is_store_live{Is store live?}
    is_store_live -->|True| is_reading{Is reading a key?}
    is_store_live -->|False| A(Kuai) --> C[/Activate a store with pattern/] --> is_reading
    is_reading -->|True| reading[/reading the key from the live store/]
    reading --> is_found{Is the key found in the store?}
    is_found -->|True| output([Output])
    is_found -->|False| D[/Activate a store with pattern/] --> E{Is new store activated?}
    E --> |True| reading
    E --> |False| output
    is_reading -->|False| is_adding{Is adding a key?}
    is_adding -->|True| F{Is store capacity enough?}
    F --> |True| add_key[/Add key in the store/]
    F --> |False| G[/Expand the store/]
    G --> H{Is the store expanded?}
    H --> |True| F
    H --> |False| output
    add_key --> output
    is_adding -->|False| is_deleting{Is deleting a key?}
    is_deleting --> |True| I[/Locate a store contains the key, similar to reading a key from store/]
    I --> J[/Clear the specified key/] --> output
    is_deleting --> |False| is_updating{Is updating a key?}
    is_updating --> |True| K{Is store capacity enough?}
    K --> |True| L[/Update the specified key/] --> output
    K --> |False| M[/Expand the store and update the key/] --> output
    is_updating --> |False| output
```

**Comment by Keith-CY** [comment]
I'll complete the document by 12/16

**Comment by Keith-CY** [comment]
This issue was postponed because I was ill

**Comment by Keith-CY** [comment]
This is an on-chain treelink-like app, it aggregates info cells belonging to a specific lock script and provides a service to fetch data from these cells by a pre-defined schema.

This service exposes the following APIs to read and write user info into cells:

1. `claim(capacity): Transaction`: claim a group of cells with a given capacity as the user info `Store` to store user info
2. `read(path): any`: fetch the value at the specific path from the user info store
3. `load(): object`: fetch the entire structured user info
4. `set(path, value): Transaction`: upsert the value at the specified path
5. `clear(): Transaction`: remove all data and turn the info cells back to normal cells

This is the brief description of the MVP dapp, please append any questions if it's not clear enough @yanguoyu @PainterPuppets @zhengjianhui @Daryl-L

**Comment by Keith-CY** [comment]
It's expected to be delivered with an API service and a simple UI works with metamask

**Comment by yanguoyu** [comment]
> This is an on-chain treelink-like app, it aggregates info cells belonging to a specific lock script and provides a service to fetch data from these cells by a pre-defined schema.
> 
> This service exposes the following APIs to read and write user info into cells:
> 
> 1. `claim(capacity): Transaction`: claim a group of cells with a given capacity as the user info `Store` to store user info
> 2. `read(path): any`: fetch the value at the specific path from the user info store
> 3. `load(): object`: fetch the entire structured user info
> 4. `set(path, value): Transaction`: upsert the value at the specified path
> 5. `clear(): Transaction`: remove all data and turn the info cells back to normal cells
> 
> This is the brief description of the MVP dapp, please append any questions if it's not clear enough @yanguoyu @PainterPuppets @zhengjianhui @Daryl-L

`claim(capacity)` may need a partial parameter to set `user info` with create a new cell. `claim(capacity, userInfo?)`

**Comment by Keith-CY** [comment]
> > This is an on-chain treelink-like app, it aggregates info cells belonging to a specific lock script and provides a service to fetch data from these cells by a pre-defined schema.
> > This service exposes the following APIs to read and write user info into cells:
> > 
> > 1. `claim(capacity): Transaction`: claim a group of cells with a given capacity as the user info `Store` to store user info
> > 2. `read(path): any`: fetch the value at the specific path from the user info store
> > 3. `load(): object`: fetch the entire structured user info
> > 4. `set(path, value): Transaction`: upsert the value at the specified path
> > 5. `clear(): Transaction`: remove all data and turn the info cells back to normal cells
> > 
> > This is the brief description of the MVP dapp, please append any questions if it's not clear enough @yanguoyu @PainterPuppets @zhengjianhui @Daryl-L
> 
> `claim(capacity)` may need a partial parameter to set `user info` with creating a new cell. `claim(capacity, userInfo?)`

Sure, `user info` is always required for every action, I didn't add it in the parameter list because it's always used and could be passed in various ways(cookie, token, etc.)

**Comment by Keith-CY** [comment]
I'll add the service of checking nodes

**Comment by yanguoyu** [comment]
> Sure, user info is always required for every action, I didn't add it in the parameter list because it's always used and could be passed in various ways(cookie, token, etc.)

I just say `userInfo` to give an example, sometimes it's other information. I mean may need a partial parameter to set initial info with creating a new cell. Like this, `claim(capacity, initialData?)`

**Comment by Keith-CY** [comment]
> > Sure, user info is always required for every action, I didn't add it in the parameter list because it's always used and could be passed in various ways(cookie, token, etc.)
> 
> I just say `userInfo` to give an example, sometimes it's other information. I mean may need a partial parameter to set initial info with creating a new cell. Like this, `claim(capacity, initialData?)`

Good point, it should be considered from the perspective of dapp, we may add more details in the API along with development
