### ISSUE TITLE
launch a local network for testing

### ISSUE THREAD

**Issue by homura** [ckb-js/kuai#8]
## Description

As a dApp user, I want the local network to be simple enough to use out of the box.

We can take a cue from `hardhat node`

<pre>
> npx hardhat node
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/

Accounts
========

WARNING: These accounts, and their private keys, are publicly known.
Any funds sent to them on Mainnet or any other live network WILL BE LOST.

Account #0: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 (10000 ETH)
Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

Account #1: 0x70997970c51812dc3a010c7d01b50e0d17dc79c8 (10000 ETH)
Private Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

Account #2: 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc (10000 ETH)
Private Key: 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
</pre>

1. out of box, no config required
2. 20 key pairs with assets (10000 ETH) are provided by default

Since CKB does not have a tool like Ganache (Tippy is written in C# and it is outdated) now, we can use CKB with a default config for the testing purpose as local network at first

Kuai is likely to write contracts in C/Rust in the long term, so we can't live without the RISC-V toolchain, which means we will be depending on Docker, so the local network can also depend on Docker directly, which will require Docker on the developer's machine

## Reference

- Docker [image](https://hub.docker.com/layers/nervos/ckb/merge-indexer-customize/images/sha256-62d5b54797931f02766258cc92c1e6e57cddaa689b3fbb3029c11da0ca6a4de2?context=explore)
- [dev config](https://github.com/homura/ckb-dev/blob/main/devnet/ckb/dev.toml)

**Comment by PainterPuppets** [comment]
## How Hardhat uses the built-in network to help with testing

hardhat has a `HardhatNode` class, this class storage the block state, has a built-in evm to process contracts and transactions, provides some function like `mining block`, and by default, it mines a block with each transaction that it receives, in order and with no delay.

`HardhatNetworkProvider` is a provider that implements the EIP1193 interface,  and use `HardhatNode` to interact with chains

`HardhatNetworkProvider` will be placed in context as lazy load when running the cli command

When running `hardhat test`, hardhat network will be used by default

Note :
 - hardhat node and test code are in the same thread, no need through the network, and there is no delay in processing transactions.
 - In the test does not automatically create multiple nodes, if you need to create multiple nodes need to be handled manually. So transactions between different tests may conflict

When running `hardhat node`, an http server will be created to host `HardhatNetworkProvider`


## How kuai to run built-in network design

Ckb currently has no way to start in memory like `HardhatNode`.

A more feasible solution at the moment seems to be to just have a `CkbNodeManager` class to manage the turning on and off of nodes

``` ts
interface CkbNodeConfig {
	repository?: string,
	tag?: string,
}

interface CkbNode {
	id: string,
	url: string,
	outputStream: Readble,
	…. // some config
}

class CkbNodeManager{
	private _ckbNodes: Array<CkbNode>;

	constructor (config?: CkbNodeConfig)
 	createNode: (port?: number) => Promise<CkbNode>
	close: (id: string) => Promise<void>
	closeAll: () => Promise<void>
}
```

useage
``` ts
// cli
const command = new Command('node');
command.action(async (args: Args) => {
	const manaegr =  new CkbNetworkManager();
	const defaultNode = manaegr.createNode();
	
	// set config etc…
	…
	
	// run test
	mocha.run() // or jest.run()

	manaegr.closeAll();
});



// test file

// default node
test("xxxx", async () => {
	const { rpc, indexer } = envrimoent; 
	….
})

// specific node
test("xxxx", async () => {
	const { manager } = envrimoent; 
	const node = await manaegr.createNode();
	const rpc = new RPC(node.url)
	….
})
```

**Comment by Keith-CY** [comment]
For the **How Hardhat uses the built-in network to help with testing**

I've checked `HardhatNode` class in [hardhat](https://github.com/NomicFoundation/hardhat/blob/080a25a7e188311d7e56366e1dae669db81aa2d7/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L131), it's expected to work with a js [VM](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm) so

> hardhat node and test code are in the same thread, no need through the network, and there is no delay in processing transactions.

is feasible because they're just pure javascript.

However, we don't have things like https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm yet. So the solution mentioned above said

> A more feasible solution at the moment seems to be to just have a `CkbNodeManager` class to manage the turning on and off of nodes

If the functions of `CkbNodeManager` is to turn on/off nodes, it's possibly similar to [hardhat-ganache](https://github.com/NomicFoundation/hardhat/tree/080a25a7e188311d7e56366e1dae669db81aa2d7/packages/hardhat-ganache)

which is a server

> started before running tests and scripts and stopped when finished

and a plugin

> hooks into the test and run tasks.

Refs: 
- [What is hardhat-ganache](https://github.com/NomicFoundation/hardhat/tree/080a25a7e188311d7e56366e1dae669db81aa2d7/packages/hardhat-ganache#what)

**Comment by PainterPuppets** [comment]
Perhaps a plugin system should be implemented first before integrating node and cli
